// <auto-generated />
using System;
using Bnfour.TgBots.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bnfour.TgBots.Migrations
{
    [DbContext(typeof(CatMacroBotContext))]
    partial class CatMacroBotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("Bnfour.TgBots.Entities.CatMacro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileUniqueId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Caption")
                        .IsUnique();

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.HasIndex("FileUniqueId")
                        .IsUnique();

                    b.ToTable("CatMacros", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
